stiltzkey/lib/stiltzkey_web/router.ex
defmodule StiltzkeyWeb.Router do
  use StiltzkeyWeb, :router

  import StiltzkeyWeb.Helpers.Plug.Accounts, only: [assign_user_if_exists: 2]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug StiltzkeyWeb.Helpers.Locale.Plug, "pt"
  end

  pipeline :maybe_user do
    plug StiltzkeyWeb.Helpers.Auth.AccessPipeline
    plug :assign_user_if_exists
  end

  pipeline :authenticate do
    plug StiltzkeyWeb.Helpers.Auth.EnsureAccessPipeline
    plug :assign_user_if_exists
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StiltzkeyWeb do
    pipe_through :browser

    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete],
                                              singleton: true
  end

  scope "/", StiltzkeyWeb do
    pipe_through [:browser, :maybe_user]

    get "/", PageController, :index
  end

  scope "/profile", StiltzkeyWeb do
    pipe_through [:browser, :authenticate]

    resources "/", UserController, only: [:show, :edit, :update, :delete]
  end

  scope "/papyrus", StiltzkeyWeb do
    pipe_through [:browser, :authenticate]

    resources "/poems", PoemController
    resources "/poems/:poem_id/stanzas", StanzaController
    resources "/poems/:poem_id/stanzas/:stanza_id/verses", VerseController
    get "/poems/:poem_id/stanzas/:stanza_id/verses/:id/value", VerseController, :show_value

    resources "/movements", MovementController
    get "/movements/:id/verse/:verse_id/value", MovementController, :show_value
    post "/movements/:id/poet", MovementController, :add_poet
    post "/movements/:id/enthusiast", MovementController, :add_enthusiast
    post "/movements/:id/verse", MovementController, :add_verse
  end
end

stiltzkey/lib/stiltzkey_web/views/layout_view.ex
defmodule StiltzkeyWeb.LayoutView do
  use StiltzkeyWeb, :view
end

stiltzkey/lib/stiltzkey_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Stiltzkey</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="z-depth-2" role="navigation">
      <div class="nav-wrapper container">
        <a id="logo-container" href="<%= page_path(@conn, :index) %>" class="brand-logo stzk-f">
          Stiltzkey
        </a>

        <ul class="right hide-on-med-and-down">
<%= if assigns[:current_user] do %>
          <li>
            <%= link @current_user.username, to: user_path(@conn, :show, @current_user) %>
          </li>
          <li>
            <%= link gettext("Sign out"), to: session_path(@conn, :delete), method: :delete %>
          </li>
<% else %>
          <li>
            <%= link gettext("Sign in"), to: session_path(@conn, :new) %>
          </li>
          <li>
            <%= link gettext("Sign up"), to: user_path(@conn, :new) %>
          </li>
<% end %>
        </ul>

        <ul id="nav-mobile" class="sidenav">
          <li class="sidenav-header">
            <div class="row">
              <div class="col s12">
                <p class="center-align">
<%= if assigns[:current_user] do %>
                  <%= link @current_user.username, to: user_path(@conn, :show, @current_user) %>
<% else %>
                  <%= gettext "Guest" %>
<% end %>
                </p>
              </div>
            </div>

            <ul class="collapsible">
              <li>
                <a class="collapsible-header waves-effect">
                  <i class="material-icons">
                    <span class="stzk-icon stzk-c-content stzk-language">
                      language
                    </span>
                  </i>
                  <span class="stzk-language">
                    <%= gettext "Language" %>
                  </span>
                </a>
                <div class="collapsible-body z-depth-3">
                  <ul>
                    <li>
                      <a href="<%= page_path(@conn, :index, locale: :en) %>" class="waves-effect">
                        <img src="/images/country_flag_us.svg" class="stzk-country"></img>
                        <span class="stzk-language-li">
                          English
                        </span>
                      </a>
                    </li>
                    <li>
                      <a href="<%= page_path(@conn, :index, locale: :pt) %>" class="waves-effect">
                        <img src="/images/country_flag_br.svg" class="stzk-country"></img>
                        <span class="stzk-language-li">
                          Português
                        </span>
                      </a>
                    </li>
                    <li>
                      <div class="divider stzk-bg-primary"></div>
                    </li>
                  </ul>
                </div>
              </li>
            </ul>
          </li>

<%= if assigns[:current_user] do %>
          <li class="stzk-bg-primary-l">
            <a href="<%= user_path(@conn, :show, @current_user) %>" class="waves-effect">
              <i class="material-icons">
                <span class="stzk-icon stzk-c-content">
                  account_circle
                </span>
              </i>
              <%= gettext "My Profile" %>
            </a>
          </li>

          <li class="stzk-bg-primary-l">
            <a href="<%= poem_path(@conn, :index) %>" class="waves-effect">
              <i class="material-icons">
                <span class="stzk-c-content">
                  chrome_reader_mode
                </span>
              </i>
              <%= gettext "My Poems" %>
            </a>
          </li>

          <li class="stzk-bg-primary-l">
            <a href="<%= movement_path(@conn, :index) %>" class="waves-effect">
              <i class="material-icons">
                <span class="stzk-c-content">
                  screen_share
                </span>
              </i>
              <%= gettext "My Movements" %>
            </a>
          </li>

          <li class="stzk-bg-primary-l">
            <a href="#" data-csrf="<%= get_csrf_token() %>" data-method="delete" data-to="<%= session_path(@conn, :delete) %>" rel="nofollow" class="waves-effect">
              <i class="material-icons">
                <span class="stzk-c-content">
                  exit_to_app
                </span>
              </i>
              <%= gettext "Sign out" %>
            </a>
          </li>
<% else %>
          <li class="stzk-bg-primary-l">
            <a href="<%= session_path(@conn, :new) %>" class="waves-effect">
              <i class="material-icons">
                <span class="stzk-c-content">
                  person
                </span>
              </i>
              <%= gettext "Sign in" %>
            </a>
          </li>

          <li class="stzk-bg-primary-l">
            <a href="<%= user_path(@conn, :new) %>" class="waves-effect">
              <i class="material-icons">
                <span class="stzk-c-content">
                  person_add
                </span>
              </i>
              <%= gettext "Sign up" %>
            </a>
          </li>
<% end %>
          <li class="sidenav-footer">
            <div class="row">
              <div class="stzk-sidenav-social">
                <div class="col s2">
                  <a href="https://github.com/arkye/stiltzkey" target="_blank">
                    <i class="fa fa-lg fa-github-alt"></i>
                  </a>
                </div>
                <div class="col s2">
                  <a href="https://gitlab.com/arkye/stiltzkey" target="_blank">
                    <i class="fa fa-lg fa-gitlab"></i>
                  </a>
                </div>
                <div class="col s2">
                  <a href="https://fga.unb.br/lappis" target="_blank">
                    <i class="fa fa-lg fa-link"></i>
                  </a>
                </div>
                <div class="col s2">
                  <a href="https://chat.lappis.rocks" target="_blank">
                    <i class="fa fa-lg fa-comments"></i>
                  </a>
                </div>
                <div class="col s2">
                  <a href="https://t.me/lappisnews" target="_blank">
                    <i class="fa fa-lg fa-telegram"></i>
                  </a>
                </div>
                <div class="col s2">
                  <a href="https://gitlab.com/lappis-unb/docs" target="_blank">
                    <i class="fa fa-lg fa-wikipedia-w"></i>
                  </a>
                </div>
              </div>
            </div>
          </li>
        </ul>

        <a href="#" data-target="nav-mobile" class="sidenav-trigger">
          <i class="material-icons">
            menu
          </i>
        </a>
      </div>
    </nav>

<%= if get_flash(@conn, :info) do %>
    <div id="alert_panel" class="card-panel stzk-alert blue lighten-3">
      <%= get_flash(@conn, :info) %>
      <i id="alert_close" class="fa fa-times right"></i>
    </div>
<% end %>

<%= if get_flash(@conn, :error) do %>
    <div id="alert_panel" class="card-panel stzk-alert red lighten-3">
        <%= get_flash(@conn, :error) %>
        <i id="alert_close" class="fa fa-times right"></i>
    </div>
<% end %>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>
      $("select").formSelect();
      $(".collapsible").collapsible();
      $(".parallax").parallax();
      $(".sidenav").sidenav();
      $(".tooltip").tooltip();
      $("#alert_close").click(function () {
        $("#alert_panel").fadeOut( "slow", function(){});
      });
    </script>
  </body>
</html>