stiltzkey/lib/stiltzkey_web/router.ex
defmodule StiltzkeyWeb.Router do
  use StiltzkeyWeb, :router

  import StiltzkeyWeb.Helpers.Plug.Accounts, only: [assign_user_if_exists: 2]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug StiltzkeyWeb.Helpers.Locale.Plug, "pt"
  end

  pipeline :maybe_user do
    plug StiltzkeyWeb.Helpers.Auth.AccessPipeline
    plug :assign_user_if_exists
  end

  pipeline :authenticate do
    plug StiltzkeyWeb.Helpers.Auth.EnsureAccessPipeline
    plug :assign_user_if_exists
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StiltzkeyWeb do
    pipe_through :browser

    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete],
                                              singleton: true
  end

  scope "/", StiltzkeyWeb do
    pipe_through [:browser, :maybe_user]

    get "/", PageController, :index
  end

  scope "/profile", StiltzkeyWeb do
    pipe_through [:browser, :authenticate]

    resources "/", UserController, only: [:show, :edit, :update, :delete]
  end

  scope "/papyrus", StiltzkeyWeb do
    pipe_through [:browser, :authenticate]

    resources "/poems", PoemController
    resources "/poems/:poem_id/stanzas", StanzaController
    resources "/poems/:poem_id/stanzas/:stanza_id/verses", VerseController
    get "/poems/:poem_id/stanzas/:stanza_id/verses/:id/value", VerseController, :show_value

    resources "/movements", MovementController
    get "/movements/:id/verse/:verse_id/value", MovementController, :show_value
    post "/movements/:id/poet", MovementController, :add_poet
    post "/movements/:id/enthusiast", MovementController, :add_enthusiast
    post "/movements/:id/verse", MovementController, :add_verse
  end
end

stiltzkey/lib/stiltzkey/papyrus/verse.ex
defmodule Stiltzkey.Papyrus.Verse do
  use Ecto.Schema
  import Ecto.Changeset

  alias Ecto.Changeset
  alias Stiltzkey.Papyrus.{Author, Movement, Stanza, Verse}

  schema "verses" do
    field :key, :string
    field :value, :string

    belongs_to :author, Author
    belongs_to :stanza, Stanza

    many_to_many :movements, Movement, join_through: "movements_verses"

    timestamps()
  end

  @doc false
  def changeset(%Verse{} = verse, attrs) do
    verse
    |> cast(attrs, [:key, :value])
    |> validate_required([:key, :value])
    |> hash_value()
  end

  defp hash_value(%Changeset{} = changeset) do
    case changeset do
      %Changeset{valid?: true, changes: %{value: value}} ->
        put_change(changeset, :value, Cipher.encrypt(value))
      _ ->
        changeset
    end
  end
end

stiltzkey/lib/stiltzkey_web/controllers/verse_controller.ex
defmodule StiltzkeyWeb.VerseController do
  use StiltzkeyWeb, :controller

  import StiltzkeyWeb.Helpers.Plug.Papyrus, only: [assign_author: 2]

  plug :assign_author
  plug :require_stanza
  plug :require_stanza_ownership when action in [:index]
  plug :authorize_if_author when action in [:show, :show_value, :edit, :update, :delete]

  alias Stiltzkey.Papyrus
  alias Stiltzkey.Papyrus.Verse

  def index(conn, _params) do
    verses = Papyrus.list_verses_from_stanza(conn.assigns.stanza)
    render(conn, "index.html", verses: verses)
  end

  def new(conn, _params) do
    changeset = Papyrus.change_verse(%Verse{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"verse" => verse_params}) do
    case Papyrus.create_verse(conn.assigns.current_author, conn.assigns.stanza, verse_params) do
      {:ok, verse} ->
        conn
        |> put_flash(:info, gettext("Verse created successfully."))
        |> redirect(to: verse_path(conn, :show, conn.assigns.stanza.poem_id, conn.assigns.stanza.id, verse))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    verse = Papyrus.get_verse!(id)
    render(conn, "show.html", verse: verse)
  end

  def show_value(conn, %{"id" => id}) do
    verse = Papyrus.get_verse!(id)
    conn
    |> render("show.html", verse: verse, secret: Cipher.decrypt(verse.value))
  end

  def edit(conn, _) do
    value = Cipher.decrypt(conn.assigns.verse.value)
    verse = %{ conn.assigns.verse | value: value }
    changeset = Papyrus.change_verse(verse)
    render(conn, "edit.html", changeset: changeset)
  end

  def update(conn, %{"verse" => verse_params}) do
    case Papyrus.update_verse(conn.assigns.verse, verse_params) do
      {:ok, verse} ->
        conn
        |> put_flash(:info, gettext("Verse updated successfully."))
        |> redirect(to: verse_path(conn, :show, conn.assigns.stanza.poem_id, conn.assigns.stanza.id, verse))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", changeset: changeset)
    end
  end

  def delete(conn, _) do
    {:ok, _verse} = Papyrus.delete_verse(conn.assigns.verse)

    conn
    |> put_flash(:info, gettext("Verse deleted successfully."))
    |> redirect(to: verse_path(conn, :index, conn.assigns.stanza.poem_id, conn.assigns.stanza.id))
  end

  defp require_stanza(conn, _) do
    stanza = Papyrus.get_stanza!(conn.path_params["stanza_id"])
    assign(conn, :stanza, stanza)
  end

  defp require_stanza_ownership(conn, _) do
    if conn.assigns.stanza.author_id == conn.assigns.current_author.id do
      conn
    else
      conn
      |> put_flash(:error, gettext("You can't see that verses."))
      |> redirect(to: page_path(conn, :index))
      |> halt()
    end
  end

  defp authorize_if_author(conn, _) do
    verse = Papyrus.get_verse!(conn.params["id"])

    if conn.assigns.current_author.id == verse.author_id do
      assign(conn, :verse, verse)
    else
      conn
      |> put_flash(:error, gettext("You can't see or modify that verse"))
      |> redirect(to: verse_path(conn, :index, conn.assigns.stanza.poem_id, conn.assigns.stanza.id))
      |> halt()
    end
  end
end

stiltzkey/lib/stiltzkey_web/views/verse_view.ex
defmodule StiltzkeyWeb.VerseView do
  use StiltzkeyWeb, :view

  import StiltzkeyWeb.Helpers.Input.Decorator

  alias Stiltzkey.Papyrus

  def author_user(%Papyrus.Verse{author: author}) do
    author.user
  end

  def author_username(%Papyrus.Verse{author: author}) do
    author.user.username
  end
end

stiltzkey/lib/stiltzkey_web/templates/verse/edit.html.eex
<div class="container">

  <br>
  <br>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-le xl6 offset-xl3">
      <h5>
<%= link to: page_path(@conn, :index) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Home" %>">
          home
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: poem_path(@conn, :index) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "My Poems" %>">
          chrome_reader_mode
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: poem_path(@conn, :show, @stanza.poem) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Poem" %>: <%= @stanza.poem.title %>">
          book
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: stanza_path(@conn, :index, @stanza.poem) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "%{poem} Stanzas", poem: @stanza.poem.title %>">
          line_style
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: stanza_path(@conn, :show, @stanza.poem, @stanza) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Stanza" %>: <%= @stanza.context %>">
          view_headline
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: verse_path(@conn, :index, @stanza.poem, @stanza) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "%{stanza} Verses", stanza: @stanza.context %>">
          format_list_bulleted
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: verse_path(@conn, :show, @stanza.poem, @stanza, @verse) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Verse" %>: <%= @verse.key %>">
          drag_handle
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
        <i class="material-icons stzk-icon stzk-c-primary tooltip" data-position="bottom" data-tooltip="<%= gettext "Edit" %>">
          edit
        </i>
      </h5>
    </div>
  </div>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-l2 xl6 offset-xl3">
      <div class="card z-depth-3">
        <h4 class="header valign-wrapper">
          <i class="material-icons stzk-icon">
            view_headline
          </i>
          <%= gettext "Edit Verse" %>
        </h4>
        <%= render "form.html", Map.put(assigns, :action, verse_path(@conn, :update, @stanza.poem, @stanza, @verse)) %>
      </div>
    </div>
  </div>
</div>

stiltzkey/lib/stiltzkey_web/templates/verse/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
<div class="card-content">

<%= if @changeset.action do %>
  <div id="alert_panel" class="row">
    <div class="col s12">
      <div class="card-panel red lighten-3 z-depth-3 black-text">
        <%= gettext "Oops, something went wrong! Please check the errors below." %>
        <i id="alert_close" class="fa fa-times right"></i>
      </div>
    </div>
  </div>
<% end %>

  <div class="input-field">
    <i class="material-icons stzk-icon prefix">
      info
    </i>
    <%= text_input f, :key, class: class_decorate(f, :key) %>
    <%= label f, :key, do: gettext("Key") %>
    <%= error_tag f, :key %>
  </div>

  <div class="input-field">
    <i class="material-icons stzk-icon prefix">
      visibility
    </i>
    <%= text_input f, :value, class: class_decorate(f, :value) %>
    <%= label f, :value, do: gettext("Value") %>
    <%= error_tag f, :value %>
  </div>
</div>

<div class="card-action">
  <%= submit "Submit", class: "btn-small" %>
</div>
<% end %>

stiltzkey/lib/stiltzkey_web/templates/verse/index.html.eex
<div class="container">

  <br>
  <br>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-le xl6 offset-xl3">
      <h5>
<%= link to: page_path(@conn, :index) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Home" %>">
          home
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: poem_path(@conn, :index) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "My Poems" %>">
          chrome_reader_mode
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: poem_path(@conn, :show, @stanza.poem) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Poem" %>: <%= @stanza.poem.title %>">
          book
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: stanza_path(@conn, :index, @stanza.poem) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "%{poem} Stanzas", poem: @stanza.poem.title %>">
          line_style
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: stanza_path(@conn, :show, @stanza.poem, @stanza) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Stanza" %>: <%= @stanza.context %>">
          view_headline
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
        <i class="material-icons stzk-icon stzk-c-primary tooltip" data-position="bottom" data-tooltip="<%= gettext "%{stanza} Verses", stanza: @stanza.context %>">
          format_list_bulleted
        </i>
      </h5>
    </div>
  </div>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-l2 xl6 offset-xl3">

      <div class="card z-depth-3">
        <h4 class="header valign-wrapper">
          <i class="material-icons stzk-icon">
            format_list_bulleted
          </i>
          <%= gettext "%{stanza} Verses", stanza: @stanza.context %>
        </h4>
        <div class="card-content">
          <ul class="collapsible">
<%= for verse <- @verses do %>
            <li>
              <div class="collapsible-header">
                <%= verse.key %>
              </div>
              <div class="collapsible-body stzk-bg-primary-l">
                <div class="card-action center">
                  <%= link gettext("Show"), to: verse_path(@conn, :show, @stanza.poem, @stanza, verse) %>
                  <%= link gettext("Edit"), to: verse_path(@conn, :edit, @stanza.poem, @stanza, verse) %>
                  <%= link gettext("Delete"), to: verse_path(@conn, :delete, @stanza.poem, @stanza, verse), method: :delete, data: [confirm: gettext("Are you sure?")] %>
                </div>
              </div>
            </li>
<% end %>
          </ul>
        </div>
        <div class="card-action">
          <%= link gettext("New %{stanza}'s Verse", stanza: @stanza.context), to: verse_path(@conn, :new, @stanza.poem, @stanza) %>
        </div>
      </div>
    </div>
  </div>
</div>

stiltzkey/lib/stiltzkey_web/templates/verse/new.html.eex
<div class="container">

  <br>
  <br>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-le xl6 offset-xl3">
      <h5>
<%= link to: page_path(@conn, :index) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Home" %>">
          home
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: poem_path(@conn, :index) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "My Poems" %>">
          chrome_reader_mode
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: poem_path(@conn, :show, @stanza.poem) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Poem" %>: <%= @stanza.poem.title %>">
          book
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: stanza_path(@conn, :index, @stanza.poem) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "%{poem} Stanzas", poem: @stanza.poem.title %>">
          line_style
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: stanza_path(@conn, :show, @stanza.poem, @stanza) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Stanza" %>: <%= @stanza.context %>">
          view_headline
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: verse_path(@conn, :index, @stanza.poem, @stanza) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "%{stanza} Verses", stanza: @stanza.context %>">
          format_list_bulleted
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
        <i class="material-icons stzk-icon stzk-c-primary tooltip" data-position="bottom" data-tooltip="<%= gettext "New" %>">
          add
        </i>
      </h5>
    </div>
  </div>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-l2 xl6 offset-xl3">
      <div class="card z-depth-3">
        <h4 class="header valign-wrapper">
          <i class="material-icons stzk-icon">
            drag_handle
          </i>
          <%= gettext "New Verse" %>
        </h4>
        <%= render "form.html", Map.put(assigns, :action, verse_path(@conn, :create, @stanza.poem_id, @stanza.id)) %>
      </div>
    </div>
  </div>
</div>

stiltzkey/lib/stiltzkey_web/templates/verse/show.html.eex
<div class="container">

  <br>
  <br>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-le xl6 offset-xl3">
      <h5>
<%= link to: page_path(@conn, :index) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Home" %>">
          home
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: poem_path(@conn, :index) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "My Poems" %>">
          chrome_reader_mode
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: poem_path(@conn, :show, @stanza.poem) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Poem" %>: <%= @stanza.poem.title %>">
          book
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: stanza_path(@conn, :index, @stanza.poem) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "%{poem} Stanzas", poem: @stanza.poem.title %>">
          line_style
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: stanza_path(@conn, :show, @stanza.poem, @stanza) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Stanza" %>: <%= @stanza.context %>">
          view_headline
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: verse_path(@conn, :index, @stanza.poem, @stanza) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "%{stanza} Verses", stanza: @stanza.context %>">
          format_list_bulleted
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
        <i class="material-icons stzk-icon stzk-c-primary tooltip" data-position="bottom" data-tooltip="<%= gettext "Verse" %>: <%= @verse.key %>">
          drag_handle
        </i>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= if assigns[:secret] do %>
<%= link to: verse_path(@conn, :show, @stanza.poem, @stanza, @verse) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Click to hide the secret value" %>">
          visibility
        </i>
<% end %>
<% else %>
<%= link to: verse_path(@conn, :show_value, @stanza.poem, @stanza, @verse) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Click to show the secret value" %>">
          visibility_off
        </i>
<% end %>
<% end %>
      </h5>
    </div>
  </div>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-l2 xl6 offset-xl3">
      <div class="card z-depth-3">
        <h4 class="header valign-wrapper">
          <i class="material-icons stzk-icon">
            view_headline
          </i>
          <%= gettext "Show Verse" %>
        </h4>
        <div class="card-content">

<%= link to: user_path(@conn, :show, @stanza.author.user) do %>
          <div class="input-field stzk-c-content">
            <i class="material-icons stzk-icon prefix">
              person
            </i>
            <input disabled value="<%= author_username(@verse) %>" type="text" class="stzk-c-content">
            <label class="stzk-c-content">
              <%= gettext("Author") %>
            </label>
          </div>
<% end %>

<%= link to: poem_path(@conn, :show, @stanza.poem) do %>
          <div class="input-field stzk-c-content">
            <i class="material-icons stzk-icon prefix">
              book
            </i>
            <input disabled value="<%= @stanza.poem.title %>" type="text" class="stzk-c-content">
            <label class="stzk-c-content">
              <%= gettext("Poem") %>
            </label>
          </div>
<% end %>

<%= link to: stanza_path(@conn, :show, @stanza.poem, @stanza) do %>
          <div class="input-field stzk-c-content">
            <i class="material-icons stzk-icon prefix">
              view_headline
            </i>
            <input disabled value="<%= @stanza.context %>" type="text" class="stzk-c-content">
            <label class="stzk-c-content">
              <%= gettext("Stanza") %>
            </label>
          </div>
<% end %>

          <div class="input-field stzk-c-content">
            <i class="material-icons stzk-icon prefix">
              info
            </i>
            <input disabled value="<%= @verse.key %>" type="text" class="stzk-c-content">
            <label class="stzk-c-content">
              <%= gettext("Key") %>
            </label>
          </div>

          <div class="input-field stzk-c-content">
<%= if assigns[:secret] do %>
            <i class="material-icons stzk-icon prefix">
              visibility
            </i>
            <input disabled value="<%= @secret %>" type="text" class="stzk-c-content">
<% else %>
            <i class="material-icons stzk-icon prefix">
              visibility_off
            </i>
            <input disabled value="********" type="text" class="stzk-c-content">
<% end %>
            <label class="stzk-c-content">
              <%= gettext("Value") %>
            </label>
          </div>
        </div>
        <div class="card-action">
<%= if assigns[:secret] do %>
          <%= link gettext("Hide Secret Value"), to: verse_path(@conn, :show, @stanza.poem, @stanza, @verse) %>
<% else %>
          <%= link gettext("Show Secret Value"), to: verse_path(@conn, :show_value, @stanza.poem, @stanza, @verse) %>
<% end %>
          <%= link gettext("Edit"), to: verse_path(@conn, :edit, @stanza.poem, @stanza, @verse) %>
          <%= link gettext("Delete"), to: verse_path(@conn, :delete, @stanza.poem, @stanza, @verse), method: :delete, data: [confirm: gettext("Are you sure?")] %>
        </div>
      </div>
    </div>
  </div>
</div>