stiltzkey/lib/stiltzkey_web/router.ex
defmodule StiltzkeyWeb.Router do
  use StiltzkeyWeb, :router

  import StiltzkeyWeb.Helpers.Plug.Accounts, only: [assign_user_if_exists: 2]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug StiltzkeyWeb.Helpers.Locale.Plug, "pt"
  end

  pipeline :maybe_user do
    plug StiltzkeyWeb.Helpers.Auth.AccessPipeline
    plug :assign_user_if_exists
  end

  pipeline :authenticate do
    plug StiltzkeyWeb.Helpers.Auth.EnsureAccessPipeline
    plug :assign_user_if_exists
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StiltzkeyWeb do
    pipe_through :browser

    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete],
                                              singleton: true
  end

  scope "/", StiltzkeyWeb do
    pipe_through [:browser, :maybe_user]

    get "/", PageController, :index
  end

  scope "/profile", StiltzkeyWeb do
    pipe_through [:browser, :authenticate]

    resources "/", UserController, only: [:show, :edit, :update, :delete]
  end

  scope "/papyrus", StiltzkeyWeb do
    pipe_through [:browser, :authenticate]

    resources "/poems", PoemController
    resources "/poems/:poem_id/stanzas", StanzaController
    resources "/poems/:poem_id/stanzas/:stanza_id/verses", VerseController
    get "/poems/:poem_id/stanzas/:stanza_id/verses/:id/value", VerseController, :show_value

    resources "/movements", MovementController
    get "/movements/:id/verse/:verse_id/value", MovementController, :show_value
    post "/movements/:id/poet", MovementController, :add_poet
    post "/movements/:id/enthusiast", MovementController, :add_enthusiast
    post "/movements/:id/verse", MovementController, :add_verse
  end
end

stiltzkey/lib/stiltzkey/papyrus/stanza.ex
defmodule Stiltzkey.Papyrus.Stanza do
  use Ecto.Schema
  import Ecto.Changeset

  alias Stiltzkey.Papyrus.{Author, Poem, Verse}

  schema "stanzas" do
    field :context, :string
    field :description, :string

    has_many :verses, Verse

    belongs_to :author, Author
    belongs_to :poem, Poem

    timestamps()
  end

  @doc false
  def changeset(stanza, attrs) do
    stanza
    |> cast(attrs, [:context, :description])
    |> validate_required([:context, :description])
  end
end

stiltzkey/lib/stiltzkey_web/controllers/stanza_controller.ex
defmodule StiltzkeyWeb.StanzaController do
  use StiltzkeyWeb, :controller

  import StiltzkeyWeb.Helpers.Plug.Papyrus, only: [assign_author: 2]

  plug :assign_author
  plug :require_poem
  plug :require_poem_ownership when action in [:index]
  plug :authorize_if_author when action in [:show, :edit, :update, :delete]

  alias Stiltzkey.Papyrus
  alias Stiltzkey.Papyrus.Stanza

  def index(conn, _params) do
    stanzas = Papyrus.list_stanzas_from_poem(conn.assigns.poem)
    render(conn, "index.html", stanzas: stanzas)
  end

  def new(conn, _params) do
    changeset = Papyrus.change_stanza(%Stanza{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"stanza" => stanza_params}) do
    case Papyrus.create_stanza(conn.assigns.current_author, conn.assigns.poem, stanza_params) do
      {:ok, stanza} ->
        conn
        |> put_flash(:info, gettext("Stanza created successfully."))
        |> redirect(to: stanza_path(conn, :show, conn.assigns.poem.id, stanza))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    stanza = Papyrus.get_stanza!(id)
    render(conn, "show.html", stanza: stanza)
  end

  def edit(conn, _) do
    changeset = Papyrus.change_stanza(conn.assigns.stanza)
    render(conn, "edit.html", changeset: changeset)
  end

  def update(conn, %{"stanza" => stanza_params}) do
    case Papyrus.update_stanza(conn.assigns.stanza, stanza_params) do
      {:ok, stanza} ->
        conn
        |> put_flash(:info, gettext("Stanza updated successfully."))
        |> redirect(to: stanza_path(conn, :show, conn.assigns.poem.id, stanza))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", changeset: changeset)
    end
  end

  def delete(conn, _) do
    {:ok, _stanza} = Papyrus.delete_stanza(conn.assigns.stanza)

    conn
    |> put_flash(:info, gettext("Stanza deleted successfully."))
    |> redirect(to: stanza_path(conn, :index, conn.assigns.poem.id))
  end

  defp require_poem(conn, _) do
    poem = Papyrus.get_poem!(conn.path_params["poem_id"])
    assign(conn, :poem, poem)
  end

  defp require_poem_ownership(conn, _) do
    if conn.assigns.poem.author_id == conn.assigns.current_author.id do
      conn
    else
      conn
      |> put_flash(:error, gettext("You can't see that stanzas."))
      |> redirect(to: page_path(conn, :index))
      |> halt()
    end
  end

  defp authorize_if_author(conn, _) do
    stanza = Papyrus.get_stanza!(conn.params["id"])

    if conn.assigns.current_author.id == stanza.author_id do
      assign(conn, :stanza, stanza)
    else
      conn
      |> put_flash(:error, gettext("You can't see or modify that stanza."))
      |> redirect(to: stanza_path(conn, :index, conn.assigns.poem.id))
      |> halt()
    end
  end
end

stiltzkey/lib/stiltzkey_web/views/stanza_view.ex
defmodule StiltzkeyWeb.StanzaView do
  use StiltzkeyWeb, :view

  import StiltzkeyWeb.Helpers.Input.Decorator

  alias Stiltzkey.Papyrus

  def author_username(%Papyrus.Stanza{author: author}) do
    author.user.username
  end
end

stiltzkey/lib/stiltzkey_web/templates/stanza/edit.html.eex
<div class="container">

  <br>
  <br>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-le xl6 offset-xl3">
      <h5>
<%= link to: page_path(@conn, :index) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Home" %>">
          home
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: poem_path(@conn, :index) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "My Poems" %>">
          chrome_reader_mode
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: poem_path(@conn, :show, @poem) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Poem" %>: <%= @poem.title %>">
          book
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: stanza_path(@conn, :index, @poem) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "%{poem} Stanzas", poem: @poem.title %>">
          line_style
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: stanza_path(@conn, :show, @poem, @stanza) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Stanza" %>: <%= @stanza.context %>">
          view_headline
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
        <i class="material-icons stzk-icon stzk-c-primary tooltip" data-position="bottom" data-tooltip="<%= gettext "Edit" %>">
          edit
        </i>
      </h5>
    </div>
  </div>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-l2 xl6 offset-xl3">
      <div class="card z-depth-3">
        <h4 class="header valign-wrapper">
          <i class="material-icons stzk-icon">
            view_headline
          </i>
          <%= gettext "Edit Stanza" %>
        </h4>
        <%= render "form.html", Map.put(assigns, :action, stanza_path(@conn, :update, @poem, @stanza)) %>
      </div>
    </div>
  </div>
</div>

stiltzkey/lib/stiltzkey_web/templates/stanza/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
<div class="card-content">

<%= if @changeset.action do %>
  <div id="alert_panel" class="row">
    <div class="col s12">
      <div class="card-panel red lighten-3 z-depth-3 black-text">
        <%= gettext "Oops, something went wrong! Please check the errors below." %>
        <i id="alert_close" class="fa fa-times right"></i>
      </div>
    </div>
  </div>
<% end %>

  <div class="input-field">
    <i class="material-icons stzk-icon prefix">
      label
    </i>
    <%= text_input f, :context, class: class_decorate(f, :context) %>
    <%= label f, :context, do: gettext("Context") %>
    <%= error_tag f, :context %>
  </div>

  <div class="input-field">
    <i class="material-icons stzk-icon prefix">
      assignment
    </i>
    <%= text_input f, :description, class: class_decorate(f, :description) %>
    <%= label f, :description, do: gettext("Description") %>
    <%= error_tag f, :description %>
  </div>

</div>

<div class="card-action">
  <%= submit "Submit", class: "btn-small" %>
</div>
<% end %>

stiltzkey/lib/stiltzkey_web/templates/stanza/index.html.eex
<div class="container">

  <br>
  <br>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-le xl6 offset-xl3">
      <h5>
<%= link to: page_path(@conn, :index) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Home" %>">
          home
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: poem_path(@conn, :index) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "My Poems" %>">
          chrome_reader_mode
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: poem_path(@conn, :show, @poem) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Poem" %>: <%= @poem.title %>">
          book
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
        <i class="material-icons stzk-icon stzk-c-primary tooltip" data-position="bottom" data-tooltip="<%= gettext "%{poem} Stanzas", poem: @poem.title %>">
          line_style
        </i>
      </h5>
    </div>
  </div>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-l2 xl6 offset-xl3">

      <div class="card z-depth-3">
        <h4 class="header valign-wrapper">
          <i class="material-icons stzk-icon">
            line_style
          </i>
          <%= gettext "%{poem} Stanzas", poem: @poem.title %>
        </h4>
        <div class="card-content">
          <ul class="collapsible">
<%= for stanza <- @stanzas do %>
            <li>
              <div class="collapsible-header">
                <%= stanza.context %>
              </div>
              <div class="collapsible-body stzk-bg-primary-l">
                <blockquote>
                  <%= stanza.description %>
                </blockquote>
                <div class="card-action center">
                  <%= link gettext("Verses"), to: verse_path(@conn, :index, @poem.id, stanza) %>
                  <%= link gettext("Show"), to: stanza_path(@conn, :show, @poem.id, stanza) %>
                  <%= link gettext("Edit"), to: stanza_path(@conn, :edit, @poem.id, stanza) %>
                  <%= link gettext("Delete"), to: stanza_path(@conn, :delete, @poem.id, stanza), method: :delete, data: [confirm: gettext("Are you sure?")] %>
                </div>
              </div>
            </li>
<% end %>
          </ul>
        </div>
        <div class="card-action">
          <%= link gettext("New %{poem}'s Stanza", poem: @poem.title), to: stanza_path(@conn, :new, @poem.id) %>
        </div>
      </div>
    </div>
  </div>
</div>

stiltzkey/lib/stiltzkey_web/templates/stanza/new.html.eex
<div class="container">

  <br>
  <br>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-le xl6 offset-xl3">
      <h5>
<%= link to: page_path(@conn, :index) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Home" %>">
          home
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: poem_path(@conn, :index) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "My Poems" %>">
          chrome_reader_mode
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: poem_path(@conn, :show, @poem) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Poem" %>: <%= @poem.title %>">
          book
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: stanza_path(@conn, :index, @poem) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "%{poem} Stanzas", poem: @poem.title %>">
          line_style
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
        <i class="material-icons stzk-icon stzk-c-primary tooltip" data-position="bottom" data-tooltip="<%= gettext "New" %>">
          add
        </i>
      </h5>
    </div>
  </div>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-l2 xl6 offset-xl3">
      <div class="card z-depth-3">
        <h4 class="header valign-wrapper">
          <i class="material-icons stzk-icon">
            book
          </i>
          <%= gettext "New Stanza" %>
        </h4>
        <%= render "form.html", Map.put(assigns, :action, stanza_path(@conn, :create, @poem.id)) %>
      </div>
    </div>
  </div>
</div>

stiltzkey/lib/stiltzkey_web/templates/stanza/show.html.eex
<div class="container">

  <br>
  <br>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-le xl6 offset-xl3">
      <h5>
<%= link to: page_path(@conn, :index) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Home" %>">
          home
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: poem_path(@conn, :index) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "My Poems" %>">
          chrome_reader_mode
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: poem_path(@conn, :show, @poem) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "Poem" %>: <%= @poem.title %>">
          book
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
<%= link to: stanza_path(@conn, :index, @poem) do %>
        <i class="material-icons stzk-icon stzk-c-content tooltip" data-position="bottom" data-tooltip="<%= gettext "%{poem} Stanzas", poem: @poem.title %>">
          line_style
        </i>
<% end %>
        <i class="material-icons stzk-icon stzk-c-content">
          navigate_next
        </i>
        <i class="material-icons stzk-icon stzk-c-primary tooltip" data-position="bottom" data-tooltip="<%= gettext "Stanza" %>: <%= @stanza.context %>">
          view_headline
        </i>
      </h5>
    </div>
  </div>

  <div class="row">
    <div class="col s12 m10 offset-m1 l8 offset-l2 xl6 offset-xl3">
      <div class="card z-depth-3">
        <h4 class="header valign-wrapper">
          <i class="material-icons stzk-icon">
            view_headline
          </i>
          <%= gettext "Show Stanza" %>
        </h4>
        <div class="card-content">

<%= link to: user_path(@conn, :show, @stanza.author.user) do %>
          <div class="input-field stzk-c-content">
            <i class="material-icons stzk-icon prefix">
              person
            </i>
            <input disabled value="<%= author_username(@stanza) %>" type="text" class="stzk-c-content">
            <label class="stzk-c-content">
              <%= gettext("Author") %>
            </label>
          </div>
<% end %>

<%= link to: poem_path(@conn, :show, @poem) do %>
          <div class="input-field stzk-c-content">
            <i class="material-icons stzk-icon prefix">
              book
            </i>
            <input disabled value="<%= @poem.title %>" type="text" class="stzk-c-content">
            <label class="stzk-c-content">
              <%= gettext("Poem") %>
            </label>
          </div>
<% end %>

          <div class="input-field stzk-c-content">
            <i class="material-icons stzk-icon prefix">
              label
            </i>
            <input disabled value="<%= @stanza.context %>" type="text" class="stzk-c-content">
            <label class="stzk-c-content">
              <%= gettext("Context") %>
            </label>
          </div>

          <div class="input-field stzk-c-content">
            <i class="material-icons stzk-icon prefix">
              assignment
            </i>
            <input disabled value="<%= @stanza.description %>" type="text" class="stzk-c-content">
            <label class="stzk-c-content">
              <%= gettext("Description") %>
            </label>
          </div>
        </div>
        <div class="card-action">
          <%= link gettext("Verses"), to: verse_path(@conn, :index, @poem.id, @stanza) %>
          <%= link gettext("Edit"), to: stanza_path(@conn, :edit, @poem.id, @stanza) %>
          <%= link gettext("Delete"), to: stanza_path(@conn, :delete, @poem.id, @stanza), method: :delete, data: [confirm: gettext("Are you sure?")] %>
        </div>
      </div>
    </div>
  </div>
</div>